# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# This file is used by Google Cloud Build to build and deploy the application.
# See https://cloud.google.com/build/docs/build-config
steps:
  # 1. Build the container image using the Bazel toolchain.
  - name: 'eu.gcr.io/cloud-telemetry-simulation/bazel:7.2.1'
    id: 'Bazel Build and Push'
    args:
      - 'build'
      - '//dist:image_mcg_tarball'
      - '--compilation_mode=opt'
      - '--remote_cache=https://storage.googleapis.com/${_BAZEL_CACHE_BUCKET}/mcg' # Cache with GCP's Cloud Bucket Storage enabled to speed up pipeine execution. Cloud Bucket has a lifecycle policy to delete objects older than 7 days.
      - '--google_default_credentials'
      - '--remote_upload_local_results=true'

  # 2. Load the image tarball into the Docker daemon.
  # We write the image name:tag to a file to use in the next step.
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Load Image'
    entrypoint: 'bash'
    args:
      - '-c'
      - >
        docker load --input bazel-bin/dist/image_mcg_tarball/tarball.tar
        | sed 's/Loaded image.*: //'
        > /workspace/mcg_docker_image_id

  # 3. Tag the loaded image for Artifact Registry.
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Tag Image'
    entrypoint: 'bash'
    args:
      - '-c'
      - >
        docker image tag
        "$(cat /workspace/mcg_docker_image_id)"
        "${_GCP_DEPLOY_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO_NAME}/${_CLOUD_RUN_SERVICE_NAME}:${COMMIT_SHA}"

  # 4. Push the container image to Google Artifact Registry.
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push'
    args:
      - 'push'
      - "${_GCP_DEPLOY_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO_NAME}/${_CLOUD_RUN_SERVICE_NAME}:${COMMIT_SHA}"

  # 5. Deploy the new container image to Google Cloud Run.
  # This command updates the existing service with a new revision.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'services'
      - 'update'
      - "${_CLOUD_RUN_SERVICE_NAME}"
      - "--image=${_GCP_DEPLOY_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO_NAME}/${_CLOUD_RUN_SERVICE_NAME}:${COMMIT_SHA}"
      - "--region=${_GCP_DEPLOY_LOCATION}"
      - '--quiet'

options:
  logging: CLOUD_LOGGING_ONLY
