// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package mcg.test;

import "mcg/testdata/vehicle_signals_sample/subpkg/sample_speed.proto";

message engine_speed_msg {
    double speed = 1;
    subpkg.speed_unit unit = 2;
}

message car_speed_msg {
    double speed = 1;
    subpkg.speed_unit unit = 2;
    int32 sample_int = 3;
    float sample_float = 4;
}

message left_wheel_speed_msg {
    double speed = 1;
    subpkg.speed_unit unit = 2;
}
