// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package mcg.test.report;

import "mcg/testdata/vehicle_signals_sample/specific_speed.proto";
import "mcg/testdata/vehicle_signals_sample/subpkg/sample_speed_list.proto";

message speed_report {
    mcg.test.engine_speed_msg avg_eng_speed = 1;
    mcg.test.engine_speed_msg max_eng_speed = 2;
    mcg.test.engine_speed_msg min_eng_speed = 3;
    mcg.test.car_speed_msg avg_car_speed = 4;
    mcg.test.car_speed_msg max_car_speed = 5;
    mcg.test.car_speed_msg min_car_speed = 6;
    mcg.test.subpkg.speed_msg_list car_speed_list = 7;
}
