# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "inference",
    srcs = [
        "expression_resolution.go",
        "inference.go",
        "tree_shaker.go",
        "tree_shaker_support.go",
    ],
    importpath = "sdv.googlesource.com/mcg/mcg/inference",
    visibility = ["//visibility:public"],
    deps = [
        "//mcg/expressions",
        "//mcg/graph",
        "//mcg/type_resolvers",
        "//mcg/validators",
        "//third_party/aosp/sdv/telemetry/metrics_configuration:telemetry_go_proto",
        "@org_golang_google_protobuf//proto",
        "@org_golang_google_protobuf//reflect/protodesc",
        "@org_golang_google_protobuf//reflect/protoreflect",
        "@org_golang_google_protobuf//types/descriptorpb",
    ],
)

go_test(
    name = "inference_test",
    size = "small",
    srcs = [
        "export_test.go",
        "expression_resolution_test.go",
        "inference_test.go",
        "tree_shaker_support_test.go",
        "tree_shaker_test.go",
    ],
    embed = [":inference"],
    deps = [
        "//mcg/type_resolvers",
        "//third_party/aosp/sdv/telemetry/metrics_configuration:telemetry_go_proto",
        "@com_github_google_go_cmp//cmp",
        "@com_github_google_go_cmp//cmp/cmpopts",
        "@org_golang_google_protobuf//proto",
        "@org_golang_google_protobuf//reflect/protodesc",
        "@org_golang_google_protobuf//reflect/protoreflect",
        "@org_golang_google_protobuf//testing/protocmp",
        "@org_golang_google_protobuf//types/descriptorpb",
    ],
)
