load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "google_sdv_telemetry_samples_proto",
    testonly = True,
    srcs = [
        "aggregate_report_finish.proto",
        "distance_traveled.proto",
        "journey_status.proto",
        "lifecycle_triggers.proto",
    ],
    visibility = ["//visibility:public"],
)
