// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Defines field options for Diagnostics serialization.

// WARNING: This is an experimental API and not expected to be stable or final.
//          Content of the file might drastically change with further development
//          iterations.

syntax = "proto3";

import "google/protobuf/descriptor.proto";

package sdv.vsidl;

// Currently this option is only supported by libsdv_uds_serde.
// Should be moved to vsidl.proto, once supported by VSIDL toolchain.
enum ByteSize {
  // [default] keeps the proto field size unchanged.
  UNCHANGED = 0;
  // changes proto field size to 1 bytes.
  ONE = 1;
  // changes proto field size to 2 bytes.
  TWO = 2;
}

message FixedPointEncoding {
  double scale = 1;
  double offset = 2;
}

extend google.protobuf.FieldOptions {
  // Specifies byte size of the primitive field.
  // Applicable to `int32`, `uint32` and `float` (if fixed_point_encoding is also
  // specified) fields. Fields annotated with this option are required to fit into
  // corresponding byte size type and will be serialized as such:
  //
  //         |  ONE  |  TWO  | UNCHANGED |
  // ________|_______|_______|___________|
  // uint32  |   u8  |  u16  |    u32    |
  // ________|_______|_______|___________|
  // int32   |   i8  |  i16  |    i32    |
  // ________|_______|_______|___________|
  // float   |   i8  |  i16  |    i32    |
  // ________|_______|_______|___________|
  ByteSize primitive_byte_size = 50200;

  // Specifies fixed point encoding parameters for floating point fields.
  // Applicable to `float` and `double` fields. Fields annotated with this option will be
  // serialized as such:
  // _________________________________________________________________
  //               |                                                  |
  // float as i32  | ( ( (float as f64) - offset ) / scale ) as i32   |
  // ______________|__________________________________________________|
  //               |                                                  |
  // double as i64 |     ( ( double - offset ) / scale ) as i64       |
  // ______________|__________________________________________________|
  //
  // During deserialization, the reverse transformation is applied:
  // ___________________________________________________________________
  //                 |                                                  |
  // float from i32  |   ( ( i32 as f64 ) * scale + offset ) as float   |
  // ________________|__________________________________________________|
  //                 |                                                  |
  // double from i64 |   ( ( i64 as f64 ) * scale + offset ) as double  |
  // ________________|__________________________________________________|
  FixedPointEncoding fixed_point_encoding = 50201;

  // Defines if the field should be skipped during diag serialization/deserialization.
  bool skip_for_diag = 50202;
}

extend google.protobuf.EnumOptions {
  // Specifies byte size of the enum.
  // Applicable to enum *type definition*. Enums annotated with this option will be
  // serialized as such:
  //         |  ONE  |  TWO  |
  // ________|_______|_______|
  // enum    |   i8  |  i16  |
  // ________|_______|_______|
  ByteSize enum_byte_size = 50200;
}

message DiagnosticsDeclaration {
  // Diagnostics data item declaration.
  //
  // See sdv.diagnostics.data_item.DataItemService service.
  message DataItem {
    // Required. Id of the data item.
    string id = 1;

    // Required. Fully qualified name of the message that defines a structure of the data item.
    string message_name = 2;

    // Flag that indicates whether the data item is writable by the Diagnostics Manager.
    //
    // Effectively, this indicates whether the call to DataItemService::Write, is supported for this
    // data item id.
    bool is_writable = 3;
  }

  // Declaration of diagnostics data for input/output control.
  //
  // See sdv.diagnostics.io_control.IoControl service.
  message InputOutputControlData {
    // Id of the input/output control data.
    string id = 1;

    // Fully qualified name of the message that defines a structure of the data.
    string message_name = 2;
  }

  // Declaration of diagnostics routine.
  //
  // See sdv.diagnostics.routine_control.RoutineControl.
  message Routine {
    // Information about routine control method.
    message Method {
      // Fully qualified name of the request message.
      string request = 1;

      // Fully qualified name of the response message.
      string response = 2;
    }

    // Id of the routine.
    string id = 1;

    // Information about routine start method.
    //
    // See sdv.diagnostics.routine_control.RoutineControl::Start.
    Method start = 2;

    // Information about routine stop method.
    //
    // See sdv.diagnostics.routine_control.RoutineControl::Stop.
    Method stop = 3;

    // Information about routine result method.
    //
    // See sdv.diagnostics.routine_control.RoutineControl::RequestResult.
    Method result = 4;
  }

  // Declaration of diagnostics event and corresponding fault listener.
  //
  // See sdv.diagnostics.event.Event.
  // See sdv.diagnostics.fault.FaultListener.
  message Event {
    // Id of the event.
    string id = 1;

    // Fully qualified message name of the event's extended data message.
    string extended_data_message_name = 2;

    // Fault status changes which service wants to be notified of.
    //
    // See sdv.diagnostics.fault.FaultListener.StatusMask.
    int32 fault_listener_mask = 3;
  }

  // Diagnostic data items exposed by the service bundle.
  repeated DataItem data_item = 1;

  // Diagnostic data exposed for input/output control by the service bundle.
  repeated InputOutputControlData io_control = 2;

  // Diagnostic routines exposed by the service bundle.
  repeated Routine routine = 3;

  // Diagnostic events sent by the service bundle.
  repeated Event event = 4;
}
