// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package validators

// McValidator aka (Metrics Config Validator) validates the metrics configs being passed.
// List of things being validated:
//   - Uuid should not be empty.
//   - Data type triggers can refer to sources -> make sure all sources exist.
//   - Aggregators or conditional triggers can refer to triggers -> make sure all
//     triggers exist.
//   - Report configs can refer to triggers -> make sure all those triggers exist.
//   - Sources referring to triggers referring to sources don't cause cyclic dependencies.
//     Cycle detection is performed using topological sort. If sorting is possible, it means there
//     are no cycles.
//   - Lifecycle triggers should all map to existing triggers.
//   - EndTriggerName should not be defined if StartTriggerName is not defined.
//   - No duplicated trigger/source/report config names per type. Also no overlapping in the names
//     of sources & triggers.
//   - ConditionType of conditional source maps into a valid `pb.ConditionalTrigger_ConditionType`.
//   - Combination expression nodes should not lead into cycles and in case of unary operators, they
//     should not have the right node set. For non-unary operators, both left and right index should
//     exist. All the references should be into other existing expression nodes.
//   - Aggregators can also refer to expression nodes. All those expression nodes
//     should also exist.
//   - Metrics report configs can also refer to expression nodes. All those expression nodes
//     should also exist.
//   - FieldLeafNode type of expression nodes should only refer to existing sources.
//   - All message types referred from aggregators or metrics report configs should refer
//     to known types. Either to types which have been passed to the MCG service or so called
//     wellknown types.

import (
	"errors"
	"fmt"

	"google.golang.org/protobuf/reflect/protoreflect"

	mcgerrors "sdv.googlesource.com/mcg/mcg/errors"
	"sdv.googlesource.com/mcg/mcg/expressions"
	"sdv.googlesource.com/mcg/mcg/graph"
	"sdv.googlesource.com/mcg/mcg/mcuuid"
	"sdv.googlesource.com/mcg/mcg/type_resolvers"
	pb "sdv.googlesource.com/mcg/third_party/aosp/sdv/telemetry/metrics_configuration"
)

// McValidator should only be used through `ValidateWithoutShallowValidations` and
// `ValidateWithShallowValidations` functions to ensure the `validate` method is only called once.
type McValidator struct {
	mc                    *pb.MetricsConfig
	triggersMap           map[string]*pb.Trigger
	sourcesMap            map[string]*pb.Source
	dataTriggerNames      []string
	aggregatorSourceNames []string
	ErrorList             []*mcgerrors.StatusError
	typeResolver          *type_resolvers.EnrichedTypeResolver
	// For some cases the shallow validations have already been run earlier during the metrics configs
	// generation so we don't want to waste "computing power" to run them again. However for example
	// for the validation API it's critical to also run those.
	bypassShallowValidations bool
}

// ValidateWithoutShallowValidations is a bit lighter version of the validations and it should be
// used for validating metrics configs which have been generated by MCG tool itself and thus the
// shallow validations have already been run for the metrics configs in earlier as part of the
// generation of the metrics configs based on the API requests.
func ValidateWithoutShallowValidations(mc *pb.MetricsConfig) []*mcgerrors.StatusError {
	v := newMcValidator(mc, true /*=bypassShallowValidations*/)
	return v.validate()
}

// ValidateWithShallowValidations is a bit more thorough version of the validations and it should be
// used for validating metrics configs which have NOT been generated by MCG tool itself.
func ValidateWithShallowValidations(mc *pb.MetricsConfig) []*mcgerrors.StatusError {
	v := newMcValidator(mc, false /*=bypassShallowValidations*/)
	return v.validate()
}

// newMcValidator creates a new McValidator struct and initializes all the necessary variables and
// checks for duplicates without yet any further validations. Use this in production code instead of
// initializing the struct directly.
func newMcValidator(mc *pb.MetricsConfig, bypassShallowValidations bool) *McValidator {
	triggersMap := make(map[string]*pb.Trigger, len(mc.GetTriggers()))
	sourcesMap := make(map[string]*pb.Source, len(mc.GetSources()))
	dataTriggerNames := []string{}
	aggregatorSourceNames := []string{}
	errorList := []*mcgerrors.StatusError{}

	for _, trigger := range mc.GetTriggers() {
		if triggersMap[trigger.GetName()] != nil {
			errorList = append(errorList, mcgerrors.DuplicateTriggerName(trigger.GetName()))
			continue // keep the first instance in case of dups.
		}
		triggersMap[trigger.GetName()] = trigger

		if trigger.GetDataTrigger() != nil {
			dataTriggerNames = append(dataTriggerNames, trigger.GetName())
		}
	}

	for _, pub := range mc.GetSources() {
		if sourcesMap[pub.GetName()] != nil {
			errorList = append(errorList, mcgerrors.DuplicateSourceName(pub.GetName()))
			continue // keep the first instance in case of dups.
		}
		sourcesMap[pub.GetName()] = pub

		if pub.GetAggregator() != nil {
			aggregatorSourceNames = append(aggregatorSourceNames, pub.GetName())
		}
	}

	resolver, err := type_resolvers.NewEnrichedTypeResolverFromFileDescriptorProtos(mc.GetDescriptorProtos())
	if err != nil {
		errorList = append(errorList, mcgerrors.FileDescriptorSetDescriptorProtosFailToParse(err, 0))
	}

	return &McValidator{
		mc:                       mc,
		triggersMap:              triggersMap,
		sourcesMap:               sourcesMap,
		dataTriggerNames:         dataTriggerNames,
		aggregatorSourceNames:    aggregatorSourceNames,
		ErrorList:                errorList,
		typeResolver:             resolver,
		bypassShallowValidations: bypassShallowValidations,
	}
}

func (v *McValidator) validate() []*mcgerrors.StatusError {
	v.validateUuid()
	v.validateHasStartTriggerIfHasEndTrigger()
	v.validateLifeCycleTriggersReferToExistingTriggers()
	v.validateTriggers()
	v.validateSources()
	v.validateNoSourceTriggerCycles()
	v.validateExpressionNodes()
	v.validateMetricsReportConfigs()
	return v.ErrorList
}

func (v *McValidator) validateUuid() {
	if v.mc.GetUuid() == "" {
		v.ErrorList = append(v.ErrorList, mcgerrors.UuidMissing)
	} else {
		_, err := mcuuid.ParseBytes([]byte(v.mc.GetUuid()))
		if err != nil {
			v.ErrorList = append(v.ErrorList, mcgerrors.UuidInvalid(err))
		}
	}
}

func (v *McValidator) validateHasStartTriggerIfHasEndTrigger() {
	if v.mc.GetStartTriggerName() == "" && v.mc.GetStopTriggerName() != "" {
		v.ErrorList = append(v.ErrorList, mcgerrors.StopTriggerSetWithoutStartTrigger)
	}
}

func (v *McValidator) validateLifeCycleTriggersReferToExistingTriggers() {
	if v.mc.GetStartTriggerName() != "" && v.triggersMap[v.mc.GetStartTriggerName()] == nil {
		v.ErrorList = append(v.ErrorList, mcgerrors.StartTriggerNameNotMatchingAnyExistingTrigger(v.mc.GetStartTriggerName()))
	}

	if v.mc.GetDeactivateTriggerName() != "" && v.triggersMap[v.mc.GetDeactivateTriggerName()] == nil {
		v.ErrorList = append(v.ErrorList, mcgerrors.DeactivateTriggerNameNotMatchingAnyExistingTrigger(v.mc.GetDeactivateTriggerName()))
	}

	if v.mc.GetStopTriggerName() != "" && v.triggersMap[v.mc.GetStopTriggerName()] == nil {
		v.ErrorList = append(v.ErrorList, mcgerrors.StopTriggerNameNotMatchingAnyExistingTrigger(v.mc.GetStopTriggerName()))
	}
}

func (v *McValidator) validateTriggers() {
	for _, trigger := range v.mc.GetTriggers() {
		if !v.bypassShallowValidations {
			if err := ShallowValidateTrigger(trigger); err != nil {
				v.ErrorList = append(v.ErrorList, err)
			}
		}

		// Check all triggers listed in periodic triggers refer to existing "parent" triggers.
		if periodicTrigger := trigger.GetPeriodicTrigger(); periodicTrigger != nil {
			for _, triggerName := range periodicTrigger.GetTriggerNames() {
				if v.triggersMap[triggerName] == nil {
					v.ErrorList = append(v.ErrorList, mcgerrors.PeriodicParentTriggerNameNotMatchingAnyExistingTrigger(triggerName))
				}
			}
		}

		// Check all triggers listed in conditional triggers refer to existing "parent" triggers.
		if conditionalTrigger := trigger.GetConditionalTrigger(); conditionalTrigger != nil {
			for _, triggerName := range conditionalTrigger.GetTriggerNames() {
				if v.triggersMap[triggerName] == nil {
					v.ErrorList = append(v.ErrorList, mcgerrors.ConditionalParentTriggerNameNotMatchingAnyExistingTrigger(triggerName))
				}
			}
		}

		if dataTrigger := trigger.GetDataTrigger(); dataTrigger != nil && dataTrigger.GetSourceName() != "" {
			source := v.sourcesMap[dataTrigger.GetSourceName()]
			if source == nil {
				v.ErrorList = append(v.ErrorList, mcgerrors.DataTriggerSourceReferenceInvalid(dataTrigger.GetSourceName()))
			} else {
				// Check that data triggers do not use data sources with ON_DEMAND connection type.
				if source.GetDataSource() != nil && source.GetDataSource().GetConnectionType() == pb.DataSource_ON_DEMAND {
					v.ErrorList = append(v.ErrorList, mcgerrors.DataTriggerUsingOnDemandDataSource)
				}
			}
		}

	}
}

// fieldAssExpressionNodeReferenceIsValid ensures that the aggregators map to existing
// expression nodes.
func fieldAssExpressionNodeReferenceIsValid(fieldAss *pb.ProtoMessageBuilder_FieldAssignment, exprNodesLen uint32, sourceName string) *mcgerrors.StatusError {
	if exprIdx, ok := expressions.ExtractNodeIndex(fieldAss); ok && exprIdx >= exprNodesLen {
		return mcgerrors.AggregatorWithInvalidExpressionNodeReference(sourceName, exprIdx)
	}
	return nil
}

func (v *McValidator) validateSources() {
	exprNodesLen := uint32(len(v.mc.GetExpressionNodes()))

	for _, pub := range v.mc.GetSources() {
		if !v.bypassShallowValidations {
			if err := ShallowValidateSource(pub); err != nil {
				v.ErrorList = append(v.ErrorList, err)
			}
		}

		// Source names should also be unique from any trigger names.
		if v.triggersMap[pub.GetName()] != nil {
			v.ErrorList = append(v.ErrorList, mcgerrors.TriggerNameCollisionWithSourceName(pub.GetName()))
		}

		// Check all triggers listed in aggregators refer to existing "parent" triggers.
		if aggPub := pub.GetAggregator(); aggPub != nil {
			for _, triggerName := range aggPub.GetTriggerNames() {
				if v.triggersMap[triggerName] == nil {
					v.ErrorList = append(v.ErrorList, mcgerrors.AggregatorParentTriggerNameNotMatchingAnyExistingTrigger(triggerName))
				}
			}

			// Check that all the message types referred from the aggregators map to resolvable types.
			if messageType := aggPub.GetMessageBuilder().GetMessageType(); messageType != "" {
				if v.typeResolver == nil {
					v.ErrorList = append(v.ErrorList, mcgerrors.NoTypeResolver(messageType))
				} else if _, err := v.typeResolver.FindMessageByName(protoreflect.FullName(messageType)); err != nil {
					v.ErrorList = append(v.ErrorList, mcgerrors.UnknownMessageType(messageType))
				}
			}

			for _, fieldAss := range aggPub.GetMessageBuilder().GetFieldAssignments() {
				if err := fieldAssExpressionNodeReferenceIsValid(fieldAss, exprNodesLen, pub.GetName()); err != nil {
					v.ErrorList = append(v.ErrorList, err)
				}
			}
		}
	}
}

func (v *McValidator) validateNoSourceTriggerCycles() {
	g := newGraphForSourceAndTriggerDepsCycleChecks(v.mc)
	if _, err := g.ReverseTopologicalOrdering(); err != nil {
		var cyclicDependencyError *graph.CyclicGraphError[string]
		if errors.As(err, &cyclicDependencyError) {
			v.ErrorList = append(v.ErrorList, mcgerrors.CyclicDependency(cyclicDependencyError.Error()))
		} else {
			v.ErrorList = append(v.ErrorList, mcgerrors.InternalFromError(err))
		}
	}
}

func (v *McValidator) validateMetricsReportConfigs() {
	exprNodesLen := uint32(len(v.mc.GetExpressionNodes()))

	repNamesMap := make(map[string]bool, len(v.mc.GetMetricsReportConfigs()))
	for _, rep := range v.mc.GetMetricsReportConfigs() {
		if repNamesMap[rep.GetName()] {
			v.ErrorList = append(v.ErrorList, mcgerrors.DuplicateMetricsReportName(rep.GetName()))
		}
		if !v.bypassShallowValidations {
			if err := ShallowValidateMetricsReportConfig(rep); err != nil {
				v.ErrorList = append(v.ErrorList, err)
			}
		}
		repNamesMap[rep.GetName()] = true

		// Check that all triggers referenced from reports exist.
		for _, trigger := range rep.GetTriggerNames() {
			if v.triggersMap[trigger] == nil {
				v.ErrorList = append(v.ErrorList, mcgerrors.MetricsReportConfigWithInvalidTriggerReference(trigger))
			}
		}

		// Check that all the message types referred from the metrics report config map to resolvable types.
		if messageType := rep.GetMessageBuilder().GetMessageType(); messageType != "" {
			if v.typeResolver == nil {
				v.ErrorList = append(v.ErrorList, mcgerrors.NoTypeResolver(messageType))
			} else if _, err := v.typeResolver.FindMessageByName(protoreflect.FullName(messageType)); err != nil {
				v.ErrorList = append(v.ErrorList, mcgerrors.UnknownMessageType(messageType))
			}
		}

		// Check that all expression nodes referenced from reports exist.
		for _, fieldAss := range rep.GetMessageBuilder().GetFieldAssignments() {
			if exprIdx, ok := expressions.ExtractNodeIndex(fieldAss); ok && exprIdx >= exprNodesLen {
				v.ErrorList = append(v.ErrorList, mcgerrors.MetricsReportConfigWithInvalidExpressionNodeReference(rep.GetName(), fieldAss.GetFieldName(), exprIdx))
			}
		}
	}
}

// printErrorList is for tests only.
func (v *McValidator) printErrorList() {
	for _, err := range v.ErrorList {
		fmt.Println(err)
	}
}

func (v *McValidator) validateExpressionNodes() {
	checkedExpressionNodes := map[int]bool{}
	exprNodesLen := uint32(len(v.mc.GetExpressionNodes()))

	for i, node := range v.mc.GetExpressionNodes() {
		if errs := validateRightAndLeftChildReferences(i, node, exprNodesLen); len(errs) > 0 {
			v.ErrorList = append(v.ErrorList, errs...)
		}

		// Field leaf nodes should only refer to existing sources or valid expression nodes.
		if fieldLeafNode := node.GetFieldLeafNode(); fieldLeafNode != nil {
			hasSource := fieldLeafNode.GetSourceName() != ""
			hasExpr := fieldLeafNode.HasExpressionNodeIndex()

			if hasSource && hasExpr {
				v.ErrorList = append(v.ErrorList, mcgerrors.FieldLeafNodeWithBothSourceAndExpressionIndexSet(i))
			} else if !hasSource && !hasExpr {
				v.ErrorList = append(v.ErrorList, mcgerrors.FieldLeafNodeWithNeitherSourceNorExpressionIndexSet(i))
			} else if hasExpr {
				exprIdx := fieldLeafNode.GetExpressionNodeIndex()
				if exprIdx >= exprNodesLen {
					v.ErrorList = append(v.ErrorList, mcgerrors.FieldLeafNodeWithInvalidExpressionNodeReference(exprIdx))
				}
			} else {
				if v.sourcesMap[fieldLeafNode.GetSourceName()] == nil {
					v.ErrorList = append(v.ErrorList, mcgerrors.ExpressionNodeWithInvalidSourceReference(i, fieldLeafNode.GetSourceName()))
				}
			}
		}

		if err := validateNoExpressionNodeCycles(i, map[int]bool{}, checkedExpressionNodes, v.mc.GetExpressionNodes()); err != nil {
			v.ErrorList = append(v.ErrorList, err)
		}
	}
}

// validateRightAndLeftChildReferences checks that combination nodes have the right and left node
// properly set so that they refer to existing nodes. Also the left node should never be nil and the
// right node should be nil for unary operators but not for others operators.
func validateRightAndLeftChildReferences(idx int, node *pb.Node, exprNodesLen uint32) []*mcgerrors.StatusError {
	errorList := []*mcgerrors.StatusError{}

	if combNode := node.GetCombinationNode(); combNode != nil {
		if !combNode.HasLeftIndex() {
			errorList = append(errorList, mcgerrors.CombinationExpressionNodeDoesntHaveLeftIndexSet(idx))
		} else if leftIdx := combNode.GetLeftIndex(); leftIdx >= exprNodesLen {
			errorList = append(errorList, mcgerrors.CombinationExpressionNodeWithInvalidExpressionNodeReference(leftIdx))
		}

		if expressions.IsUnaryOperator(combNode) {
			if combNode.HasRightIndex() {
				errorList = append(errorList, mcgerrors.UnaryOperatorExpressionNodeHasRightIndexSet(idx))
			}
		} else {
			if !combNode.HasRightIndex() {
				errorList = append(errorList, mcgerrors.NonUnaryCombinationExpressionNodeDoesntHaveRightIndexSet(idx))
			} else if rightIdx := combNode.GetRightIndex(); rightIdx >= exprNodesLen {
				errorList = append(errorList, mcgerrors.CombinationExpressionNodeWithInvalidExpressionNodeReference(rightIdx))
			}
		}
	}

	return errorList
}

// validateNoExpressionNodeCycles is a recursive helper traversing through the expression nodes.
// Note that expression nodes that refer to sources may cause cycles back to the same expression
// node, but that is accepted. Field nodes only read the latest state of the source, so it's okay
// for them to depend on the source that in turn uses them to initialize its state. In fact, it
// is a feature that allows to accumulate data in aggregators by referring to themselves.
func validateNoExpressionNodeCycles(currIdx int, visited, checkedExpressionNodes map[int]bool, exprNodes []*pb.Node) *mcgerrors.StatusError {
	if currIdx >= len(exprNodes) {
		// Return gracefully as this type of error is already checked as part of
		// validateRightAndLeftChildReferences.
		return nil
	}
	if visited[currIdx] {
		return mcgerrors.CyclicDependency(fmt.Sprintf("expression_nodes[%d]", currIdx))
	}
	if checkedExpressionNodes[currIdx] {
		return nil
	}

	visited[currIdx] = true
	checkedExpressionNodes[currIdx] = true

	if combNode := exprNodes[currIdx].GetCombinationNode(); combNode != nil {
		if leftIdx := combNode.GetLeftIndex(); combNode.HasLeftIndex() {
			if err := validateNoExpressionNodeCycles(int(leftIdx), visited, checkedExpressionNodes, exprNodes); err != nil {
				return err
			}
		}

		if rightIdx := combNode.GetRightIndex(); combNode.HasRightIndex() {
			if err := validateNoExpressionNodeCycles(int(rightIdx), visited, checkedExpressionNodes, exprNodes); err != nil {
				return err
			}
		}
	}

	if fieldNode := exprNodes[currIdx].GetFieldLeafNode(); fieldNode != nil {
		if exprIdx := fieldNode.GetExpressionNodeIndex(); fieldNode.HasExpressionNodeIndex() {
			if err := validateNoExpressionNodeCycles(int(exprIdx), visited, checkedExpressionNodes, exprNodes); err != nil {
				return err
			}
		}
	}

	return nil
}
